"""the content column in the notes table can be NULL value

Revision ID: 191d1199c29d
Revises: 57011cd57c02
Create Date: 2026-10-02 21:22:45.290021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191d1199c29d'
down_revision: Union[str, Sequence[str], None] = '57011cd57c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
