"""lazy selectin for labems

Revision ID: 7698b92d5f1f
Revises: 2a382fa9a788
Create Date: 2026-08-24 14:29:57.818482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7698b92d5f1f'
down_revision: Union[str, Sequence[str], None] = '2a382fa9a788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
